-- Table: public.listings

-- DROP TABLE IF EXISTS public.listings;

CREATE TABLE IF NOT EXISTS public.listings
(
    id bigint NOT NULL DEFAULT nextval('listings_id_seq'::regclass),
    listing_url text COLLATE pg_catalog."default" NOT NULL,
    scrape_id bigint NOT NULL,
    last_scraped date NOT NULL,
    source text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    neighborhood_overview text COLLATE pg_catalog."default",
    picture_url text COLLATE pg_catalog."default" NOT NULL,
    host_id integer NOT NULL,
    host_url text COLLATE pg_catalog."default" NOT NULL,
    host_name text COLLATE pg_catalog."default",
    host_since date,
    host_location text COLLATE pg_catalog."default",
    host_about text COLLATE pg_catalog."default",
    host_response_time text COLLATE pg_catalog."default",
    host_response_rate numeric,
    host_acceptance_rate numeric,
    host_is_superhost boolean,
    host_thumbnail_url text COLLATE pg_catalog."default",
    host_picture_url text COLLATE pg_catalog."default",
    host_neighbourhood text COLLATE pg_catalog."default",
    host_listings_count integer NOT NULL,
    host_total_listings_count integer NOT NULL,
    host_verifications text COLLATE pg_catalog."default",
    host_has_profile_pic boolean,
    host_identity_verified boolean,
    neighbourhood text COLLATE pg_catalog."default",
    neighbourhood_cleansed text COLLATE pg_catalog."default" NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    property_type text COLLATE pg_catalog."default" NOT NULL,
    room_type text COLLATE pg_catalog."default" NOT NULL,
    accommodates integer NOT NULL,
    bathrooms double precision NOT NULL,
    bathrooms_text text COLLATE pg_catalog."default",
    bedrooms integer NOT NULL,
    beds integer NOT NULL,
    amenities text COLLATE pg_catalog."default",
    price double precision,
    minimum_nights integer NOT NULL,
    maximum_nights integer NOT NULL,
    minimum_minimum_nights integer NOT NULL,
    maximum_minimum_nights integer NOT NULL,
    minimum_maximum_nights integer NOT NULL,
    maximum_maximum_nights integer NOT NULL,
    minimum_nights_avg_ntm double precision NOT NULL,
    maximum_nights_avg_ntm double precision NOT NULL,
    has_availability boolean,
    availability_30 integer NOT NULL,
    availability_60 integer NOT NULL,
    availability_90 integer NOT NULL,
    availability_365 integer NOT NULL,
    calendar_last_scraped date NOT NULL,
    number_of_reviews integer NOT NULL,
    number_of_reviews_ltm integer NOT NULL,
    number_of_reviews_l30d integer NOT NULL,
    first_review date,
    last_review date,
    review_scores_rating double precision,
    review_scores_accuracy double precision,
    review_scores_cleanliness double precision,
    review_scores_checkin double precision,
    review_scores_communication double precision,
    review_scores_location double precision,
    review_scores_value double precision,
    instant_bookable boolean NOT NULL,
    calculated_host_listings_count integer NOT NULL,
    calculated_host_listings_count_entire_homes integer NOT NULL,
    calculated_host_listings_count_private_rooms integer NOT NULL,
    calculated_host_listings_count_shared_rooms integer NOT NULL,
    reviews_per_month double precision,
    bathroom_type text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT listings_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.listings
    OWNER to postgres;